modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/hypherionmc/MoreCreativeTabs/issues"

[[mods]]
modId="morecreativetabs"
version="${file.jarVersion}"
displayName="MoreCreativeTabs"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/morecreativetabs-forge-fabric"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="HypherionSA"
description='''
A mod that allows you to customize creative tabs. Add your own, move items to a custom tab or just disable vanilla tabs.
'''

[[dependencies.morecreativetabs]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morecreativetabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
